#!/bin/sh

if [ -z "${ZEPTOBLOG_HOME}" ]
then
  echo "ZEPTOBLOG_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${ZEPTOBLOG_HOME}/lib" \
-m com.io7m.zeptoblog.cmdline/com.io7m.zeptoblog.cmdline.ZBlogMain \
"$@"
